package com.techtalentsouth.TechTalentBlog.BlogPost;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


//this is the model of the MVC


@Entity
@Table(name="blogpoststable")
public class BlogPost {
	//sets the Id as the Primary Key
	@Id
	
	//allows the ID to be generated by the underlying database 
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="blogid") //connects to values
	private Long id; 
	
	@Column(name="title")
    private String title;
	@Column(name="author")
    private String author;
	@Column(name="blogentry")
    private String blogEntry;
    
    public BlogPost() {
    	//non-argument constructor needed for JPA
    }
    
    public BlogPost(String title, String author, String blogEntry) {
        this.title = title; 
        this.author = author;
	this.blogEntry = blogEntry;

    }

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getBlogEntry() {
		return blogEntry;
	}

	public void setBlogEntry(String blogEntry) {
		this.blogEntry = blogEntry;
	}
	
	public void setId(long id) {
		this.id=id;
	}

	public Long getId() {
		return id;
	}

	@Override
	public String toString() {
		return "BlogPost [id=" + id + ", title=" + title + ", author=" + author + ", blogEntry=" + blogEntry + "]";
	}
    
}
